### PR TITLE
fix getting tasks array for gulp 4

### PR DESCRIPTION
**Pull request by slyka85**
Gulp 4 version has changed the Gulp object structure, therefore getting tasks with 'gulp.tasks' is no longer available. 
The new method of getting a list of tasks is 'gulp.tree()'

### CODE REVIEW

**Comment by OverZealous** [comment]
Hey there, thanks for this!  I'll be honest, this project is basically dead. I think there's some forks that have continued to maintain it.

Because this is an easy enough change, I'd be happy to roll out a new version. Apparently it'll need to have the `.travis.yml` updated to support newer versions so it can pass the tests (I'd drop anything older than 4? Maybe 6?).

**Comment by slyka85** [comment]
cool, updated to v6. All checks passed now.

**Comment by OverZealous** [comment]
Awesome, thanks for the PR!

**Comment by OverZealous** [comment]
Published as 1.1.0!

**Pull request merged**
